export const siteConfig = {
  name: 'John Doe',
  title: 'John Doe | Front-end developer',
  description:
    "Hello, I'm John. I am front-end developer from Poland. I enjoy building sites and apps. My focus is React (Next.js).",
  keywords: [
    'John Doe',
    'Front-end developer',
    'Poland',
    'React',
    'Next.js',
    'Web development',
    'Front-end',
    'UI/UX',
    'Responsive design',
    'JavaScript',
    'HTML',
    'CSS',
    'Portfolio',
    'Projects',
    'Website',
    'Web applications',
    'Developer',
    'Code',
    'Programming',
    'Tech enthusiast',
  ],
  creator: 'Build With Rajan ',
  url: process.env.NEXT_PUBLIC_SITE_URL,
  contact: {
    email: 'rajanvimla27@gmail.com',
    linkedin: 'https://www.linkedin.com/in/rajan-yadavv/',
    github: 'https://github.com/MicrosoftRajan',
  },
  links: {
    contactForm: '/#contact',
    linkedin: 'https://www.linkedin.com/in/rajan-yadavv/',
    github: 'https://github.com/MicrosoftRajan',
    mailTo: 'rajanvimla27@gmail.com',
    cvPdf: '/Overleaf.pdf',
    rajantwitter: 'https://x.com/RRajanYadavv',
  },
}
